### ISSUE TITLE
Request for Review

### ISSUE THREAD

**Issue by BenjaminSemah** [BenjaminSemah/ruby-catalogue-app#34]
Hello Code Reviewer.

Here is a link to our [Ruby Group Capstone Project](https://github.com/BenjaminSemah/ruby-catalogue-app/projects/1)

There are three people on our team.

- Team member 1 is @zairdon20 
- Team member 2 is @BenjaminSemah 
- Team member 3 is @butlermuwo

**Comment by elisha2kyakpo1** [comment]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## All the best🎉🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenjaminSemah** [comment]
Thank you @elisha2kyakpo1
